name: AppSec IL 2023

on: push

jobs:
  appsecil: 
    runs-on: ubuntu-latest
    name: Hello World
    steps:
      - run: | 
          echo "Hellp AppSec IL"
          id
          uname -a
          env
            
