name: AppSec IL 2023

on: push

jobs:
  appsecil: 
    runs-on: ubuntu-latest
    name: Hello World
    steps:
      - run: | 
          echo "Hellp AppSec IL"
          id
          uname -a
          env
  owasp-zap:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: ZAP Scan
      uses: zaproxy/action-baseline@v0.7.0
      with:
        target: 'https://juice-shop.herokuapp.com/'

            
